Project Information in json. Temperature statistics by mast and by turbine
IEC-61400-15/site_suitability_conditions_input_form pull request #12
Opened 2024-03-18 13:54 UTC by jsrodrigo

This pull request includes the following changes:
- `Project Information` tab in the excel format was missing in the json format. 
- `Temperature` tab in the excel format has been formulated similarly to the `Frequency` tab with frequency and number of samples for measurement device and turbine sites.

2024-03-22 11:57 UTC, NievesBurillo commented
Hi Javier, 
Thanks for the help. 
It looks good to me :)
Hope the rest can also comment and we can have this closed by early next week.

2024-03-22 20:25 UTC, Dynorat commented on README.md
> +The .xlsx file and Javasript Object Notation (JSON) file are intended to faciliate and streamline data exchange between wind industry stakeholders.  The IEC team has also included a versions that hav
Should read as " The IEC team has also included a version that has been populated with example data."

2024-03-22 20:32 UTC, Dynorat commented on site_suitability_input_conditions_form_v16_20240305_with_example_data.json
> +            "COV": "N/A",
is this correct?  I think "CoV" had a specific scientific meaning.  @NievesBurillo ? @youngli-jp

2024-03-22 20:36 UTC, Dynorat requested changes
some basic comments here to be double checked.  otherwise looks good to me.  We can double check before the final version release once the repo is a bit cleaner

2024-03-22 20:36 UTC, Dynorat approved these changes
makes sense to me

2024-03-22 20:40 UTC, Dynorat reviewed
suggest adding any inline comments that might help the user understand the python script and usage.  Perhaps this is in the readme somewhere? @jsrodrigo @youngli-jp  thoguhts?

2024-03-22 20:54 UTC, Dynorat commented on site_suitability_input_conditions_form_v16_20240305_with_example_data.json
> +            "COV": "N/A",
#10 linking the related issue here for resolution

2024-04-30 04:35 UTC, jonssonchristian commented
Hi @jsrodrigo, @NievesBurillo, @Dynorat and @youngli-jp, 

I see this pull request has not been merged yet. Is there anything holding it up? If everyone is happy with the changes, can we go ahead and merge it? If there are further refinements planned, perhaps those can be covered in a separate pull request.

2024-04-30 06:18 UTC, NievesBurillo commented
Thanks for following up on this topic Christian.

From my side it is OK to proceed, if no one has comments, I actually thought it was already done.

I do not know how to do it so someone else will have to.
With best regards,
Nieves Burillo
Tel.: +45 30376316

From: Christian Jonsson ***@***.***>
Sent: 30. april 2024 06:35
To: IEC-61400-15/site_suitability_conditions_input_form ***@***.***>
Cc: Burillo, Nieves (SGRE OF S SP TES SW) ***@***.***>; Mention ***@***.***>
Subject: Re: [IEC-61400-15/site_suitability_conditions_input_form] Project Information in json. Temperature statistics by mast and by turbine (PR #12)


Hi @jsrodrigo<https://github.com/jsrodrigo>, @NievesBurillo<https://github.com/NievesBurillo>, @Dynorat<https://github.com/Dynorat> and @youngli-jp<https://github.com/youngli-jp>,

I see this pull request has not been merged yet. Is there anything holding it up? If everyone is happy with the changes, can we go ahead and merge it? If there are further refinements planned, perhaps those can be covered in a separate pull request.

-
Reply to this email directly, view it on GitHub<https://github.com/IEC-61400-15/site_suitability_conditions_input_form/pull/12#issuecomment-2084361551>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXM5C46RPTMBWVQF5Z5J2WDY74NQ5AVCNFSM6AAAAABE3UNU46VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBUGM3DCNJVGE>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-04-30 06:26 UTC, jonssonchristian commented
Hi @NievesBurillo,

Thank you very much for the feedback. I am happy to complete the merge if everyone is happy with that. I will leave a little bit of time in case anyone else has comments.

2024-05-07 03:02 UTC, jonssonchristian commented
Since there were no further comments, I go ahead and merge this pull request now.

2024-05-07 03:02 UTC, merged